config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'registrations' }
  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy'
  end
  resources :achievements

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base

  validates :name,     presence: true
  validates :user_id,  presence: true
  validates :hashtag,  presence: true, uniqueness: {scope: :user_id}
  validates :status,   presence: true

  scope :planned, -> { where(status: 'planned') }
  scope :done, -> { where(status: 'done') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  after_create :get_user_instagram_user_id

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :achievements

  private

    def get_user_instagram_user_id
      response = instagram_client.user_search(self.instagram_username)
      user_id  = response[0]["id"]
      self.update_attributes(instagram_user_id: user_id)
    end

    def instagram_client
      Instagram.client(client_id: "#{ENV['WUNSCHCONCERT_INSTAGRAM_ID']}")
    end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :set_achievement, only: [:edit, :update, :destroy]

  def index
    current_user.achievements.each do |achievement|
      if achievement.status == "planned"
        fetch_and_save_user_media(achievement)
      end
    end

    @achievements = current_user.achievements
  end

  def show
    achievement = Achievement.find(params[:id])

    if achievement.status == "planned"
      fetch_and_save_user_media(achievement)
    end

    @achievement = achievement
  end

  def new
    @achievement = Achievement.new
  end

  def edit
  end

  def create
    @achievement = Achievement.new(achievement_params.merge(user_id: current_user.id, status: 'planned'))

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to achievements_path, notice: 'Achievement was successfully created.' }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @achievement.update(achievement_params)
        format.html { redirect_to @achievement, notice: 'Achievement was successfully updated.' }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to achievements_url, notice: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def achievement_params
      params.require(:achievement).permit(:name, :description, :hashtag, :status)
    end

    def instagram_client
      Instagram.client(client_id: "#{ENV['WUNSCHCONCERT_INSTAGRAM_ID']}")
    end

    def fetch_and_save_user_media(achievement)
      # run it on action show and once a day
      response = instagram_client.user_recent_media(current_user.instagram_user_id)
      response.each do |media|
        if media["tags"].include?(achievement.hashtag)

          achievement.update_attributes(
            image_direct_link: media["images"]["standard_resolution"]["url"],
            image_instagram_link: media["link"],
            instagram_caption: media["caption"]["text"],
            status: "done"
          )
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if current_user
      redirect_to achievements_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:instagram_username, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:instagram_username, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/_form.html.haml
= form_for @achievement do |f|
  - if @achievement.errors.any?
    .alert-box.alert
      %p= "#{pluralize(@achievement.errors.count, "error")} prohibited this achievement from being saved:"
      %ul
        - @achievement.errors.full_messages.each do |message|
          %li= message

  .row
    .columns.large-12
      = f.label :name
      = f.text_field :name

  .row
    .columns.large-12
      = f.label :description
      = f.text_area :description

  .row
    .columns.large-12
      = f.label :hashtag
      = f.text_field :hashtag

  .row
    .columns.large-12
      %button.expand{ type: 'submit' }
        = 'Save'

app/views/achievements/_sidebar.html.haml
.columns.medium-3
  .profile
    = current_user.email

  %ul.side-nav
    %li.heading
      = 'Achievements list'
    %li
      = link_to 'My Personal List', achievements_path

app/views/achievements/edit.html.haml
- content_for :navbar do
  = render 'partials/navbar', user_signed_in: user_signed_in?, modifier: ''

.row
  = render 'sidebar'
  .medium-9.columns
    .row
      %h1= 'Edit achievement'

      = render 'form'

app/views/achievements/index.html.haml
- content_for :navbar do
  = render 'partials/navbar', user_signed_in: user_signed_in?, modifier: ''

.row
  = render 'sidebar'
  .medium-9.columns
    .row
      %h1= 'My personal list'
      %h4= "#{@achievements.done.count} out of #{@achievements.count} done!"

      = link_to 'New achievement', new_achievement_path, class: 'button small'

      - if @achievements
        %ol.achievements
          - @achievements.each do |achievement|
            %li
              .row
                .columns.medium-7
                  - if achievement.status == 'done'
                    %span.label.success= 'DONE'
                  - else
                    %span.label.alert= 'TO DO'
                  %h3
                    = achievement.name
                  %div= achievement.description
                  .hashtag= "##{achievement.hashtag}"
                - if achievement.image_direct_link
                  = image_tag(achievement.image_direct_link, class: 'columns medium-5')

app/views/achievements/new.html.haml
- content_for :navbar do
  = render 'partials/navbar', user_signed_in: user_signed_in?, modifier: ''

.row
  = render 'sidebar'
  .medium-9.columns
    .row
      %h1= 'New achievement'

      = render 'form'

app/views/achievements/show.html.haml
- content_for :navbar do
  = render 'partials/navbar', user_signed_in: user_signed_in?, modifier: ''

.row
  = render 'sidebar'
  .medium-9.columns
    .row
      = "Name:"
      = @achievement.name

    .row
      = "Description:"
      = @achievement.description

    .row
      = "Hashtag:"
      = @achievement.hashtag

    .row
      = "Status:"
      = @achievement.status

    - if @achievement.status == "done"
      .row
        = @achievement.instagram_caption

      .row
        = image_tag(@achievement.image_direct_link)
        %br
        = link_to "See it on instagram", @achievement.image_instagram_link, target: '_blank'

    - if @achievement.status == "planned"
      = link_to 'Edit', edit_achievement_path(@achievement)
      = '|'
    = link_to 'Back', achievements_path

app/views/landing/index.html.haml
- content_for :navbar do
  = render 'partials/navbar', modifier: '', user_signed_in: user_signed_in?

%section.intro
  %div
    %h1.claim
      = 'Life is more than a simple to-do list.'
    .slogan
      != 'Get your dreams done with <b>Wunschconcert</b>.'
    %a.button.success{ href: new_user_registration_path }
      = 'Join Wunschconcert'

app/views/layouts/application.html.haml
!!! 5
%html{ lang: 'en' }
  %head
    %meta{ charset: 'UTF-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, user-scalable=no' }
    %title= 'Wunschconcert'

    = stylesheet_link_tag :wunschconcert, media: 'all'
    = csrf_meta_tag

  %body
    = yield :navbar

    - if notice
      .alert-box.success= notice
    - if alert
      .alert-box.alert= alert

    = yield

app/views/partials/_navbar.html.haml
%nav{ class: "top-bar #{modifier}", role: 'navigation' }
  %ul.title-area
    %li.name
      %h1
        %a{ href: '/' }
          = 'Wunschconcert'
    %li.toggle-topbar.menu-icon
      %a{ href: '#' }
        = 'Menu'


  %section.top-bar-section
    %ul.right
      - if user_signed_in
        %li
          %a{ href: edit_user_registration_path }
            = 'Edit profile'
        %li
          %a{ href: destroy_user_session_path }
            = 'Logout'
      - else
        %li
          %a{ href: new_user_session_path }
            = 'Login'